apps:
  - name: "chat"
    description: "SSH group chat"
    host: "sshchat"
    port: 2022

  - name: "tobby"
    description: "IRC client (irc.h4ks.com)"
    host: "tobby"
    port: 2222
    requires_auth: true
    requires_oauth: true

  - name: "hanb"
    description: "hanb shell"
    host: "hanb"
    port: 2222

  - name: "wordle"
    description: "Wordle word game"
    host: "wordle"
    port: 1337
    group: "games"

  - name: "asshteroids"
    description: "Multiplayer Asteroids"
    host: "asshteroids"
    port: 2222
    group: "games"

  - name: "sshtron"
    description: "Multiplayer Tron"
    host: "sshtron"
    port: 2022
    group: "games"

  - name: "netris"
    description: "Multiplayer Tetris"
    host: "playnetris.com"
    port: 22
    group: "games"
    external: true
