name: ci

on:
  push:

jobs:
  lints-and-tests:
    name: Lints and Tests
    runs-on: ubuntu-latest
    # Run for every commit
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Install goimports
        run: go install golang.org/x/tools/cmd/goimports@latest
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.58
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - uses: pre-commit/action@v3.0.1
