name: ci

on:
  push:

jobs:
  lints-and-tests:
    name: Lints and Tests
    runs-on: ubuntu-latest
    # Run for every commit
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: '1.23'
      - name: Install go modules
        run: go mod download
      - name: Install go imports
        run: go install golang.org/x/tools/cmd/goimports@latest
      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - uses: pre-commit/action@v3.0.1
